export const NotificationActionTypes = {
    SEND_MAIL_REQUEST: '@@Notification/SEND_MAIL_REQUEST',
    SEND_MAIL_SUCCESS: '@@Notification/SEND_MAIL_SUCCESS',
    SEND_MAIL_FAILURE: '@@Notification/SEND_MAIL_FAILURE',

    SEND_SMS_REQUEST: '@@Notification/SEND_SMS_REQUEST',
    SEND_SMS_SUCCESS: '@@Notification/SEND_SMS_SUCCESS',
    SEND_SMS_FAILURE: '@@Notification/SEND_SMS_FAILURE',

    PUSH_NOTIFICATION_REQUEST: '@@Notification/PUSH_NOTIFICATION_REQUEST',
    PUSH_NOTIFICATION_SUCCESS: '@@Notification/PUSH_NOTIFICATION_SUCCESS',
    PUSH_NOTIFICATION_FAILURE: '@@Notification/PUSH_NOTIFICATION_FAILURE',

    UPDATE_SETTING_REQUEST: '@@Notification/UPDATE_SETTING_REQUEST',
    UPDATE_SETTING_SUCCESS: '@@Notification/UPDATE_SETTING_SUCCESS',
    UPDATE_SETTING_FAILURE: '@@Notification/UPDATE_SETTING_FAILURE',

    FETCH_PUSH_REQUEST: '@@Notification/FETCH_PUSH_REQUEST',
    FETCH_PUSH_SUCCESS: '@@Notification/FETCH_PUSH_SUCCESS',
    FETCH_PUSH_FAILURE: '@@Notification/FETCH_PUSH_FAILURE',

    READ_PUSH_REQUEST: '@@Notification/READ_PUSH_REQUEST',
    READ_PUSH_SUCCESS: '@@Notification/READ_PUSH_SUCCESS',
    READ_PUSH_FAILURE: '@@Notification/READ_PUSH_FAILURE',

    READ_ALL_PUSH_REQUEST: '@@Notification/READ_ALL_PUSH_REQUEST',
    READ_ALL_PUSH_SUCCESS: '@@Notification/READ_ALL_PUSH_SUCCESS',
    READ_ALL_PUSH_FAILURE: '@@Notification/READ_ALL_PUSH_FAILURE',

    CREATE_SETTING_REQUEST: '@@Notification/CREATE_SETTING_REQUEST',
    CREATE_SETTING_SUCCESS: '@@Notification/CREATE_SETTING_SUCCESS',
    CREATE_SETTING_FAILURE: '@@Notification/CREATE_SETTING_FAILURE',

    EDIT_SETTING_REQUEST: '@@Notification/EDIT_SETTING_REQUEST',
    EDIT_SETTING_SUCCESS: '@@Notification/EDIT_SETTING_SUCCESS',
    EDIT_SETTING_FAILURE: '@@Notification/EDIT_SETTING_FAILURE',

    FETCH_SETTING_REQUEST: '@@Notification/FETCH_SETTING_REQUEST',
    FETCH_SETTING_SUCCESS: '@@Notification/FETCH_SETTING_SUCCESS',
    FETCH_SETTING_FAILURE: '@@Notification/FETCH_SETTING_FAILURE',
    
    DELETE_SETTING_REQUEST: '@@Notification/DELETE_SETTING_REQUEST',
    DELETE_SETTING_SUCCESS: '@@Notification/DELETE_SETTING_SUCCESS',
    DELETE_SETTING_FAILURE: '@@Notification/DELETE_SETTING_FAILURE',
}